# I AM NOT DONE
"""Chapter 5: Fault Tolerance & Recovery - Exercise 3: Lineage Reconstruction & DAG Replay.

One of Ray's core distributed primitives is Object Lineage Tracking:
- Every `ObjectRef` generated by a `@ray.remote` task retains metadata about the task DAG that produced it.
- If an intermediate object in shared memory (Plasma) is evicted due to memory pressure or a node loss,
  Ray can automatically re-execute the upstream ancestor tasks to reconstruct the missing data!

To enable lineage reconstruction:
- Tasks must be deterministic functions of their inputs (avoid untracked global side effects).
- Pass `max_retries=-1` or `max_retries > 0` on upstream tasks so Ray knows they can be safely recomputed.

Example:
    @ray.remote(max_retries=3)
    def stage1(n): return [i**2 for i in range(n)]

    @ray.remote
    def stage2(data): return sum(data)

Your Task:
- Define a `@ray.remote(max_retries=3)` function `generate_numbers(count: int) -> list[int]`
  that returns `[i * 10 for i in range(count)]`.
- Define a `@ray.remote` function `aggregate_sum(numbers: list[int]) -> int` that returns
  `sum(numbers)`.
- In `verify()`:
  - Launch `generate_numbers.remote(5)` to obtain an `ObjectRef`.
  - Pass that `ObjectRef` into 2 downstream tasks: `aggregate_sum.remote(ref)` and a second consumer.
  - Verify both downstream tasks resolve correctly and share the lineage graph.
"""

import ray


# TODO: Define generate_numbers with max_retries=3
def generate_numbers(count: int) -> list[int]:
    return [i * 10 for i in range(count)]


# TODO: Define aggregate_sum remote task
def aggregate_sum(numbers: list[int]) -> int:
    return sum(numbers)


def verify() -> None:
    ray.init(ignore_reinit_error=True)

    # TODO: Build lineage DAG
    # numbers_ref = generate_numbers.remote(5)
    # sum_ref = aggregate_sum.remote(numbers_ref)
    # double_sum_ref = aggregate_sum.remote(numbers_ref)
    # sum_val, double_val = ray.get([sum_ref, double_sum_ref])
    sum_val, double_val = None, None

    assert sum_val == 100, f"Expected sum 100 (0+10+20+30+40), got {sum_val}"
    assert double_val == 100, f"Expected double sum 100, got {double_val}"
    print(f"✓ fault03 verified: Lineage DAG constructed and resolved successfully (sum={sum_val})!")
    ray.shutdown()


if __name__ == "__main__":
    verify()
